import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";
import { FaBars } from "react-icons/fa";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className + " bg-[#EFE6D4]"}>
        <div className="flex items-center bg-[#EFE6D4] border-b-2 border-[#5B2205] mx-9">
          <Link href="/">
            <Image
              src="/HomeHaven.png"
              alt="HomeHaven Logo"
              width={120}
              height={1}
              loading="eager"
              className="aspect-square min-w-fit"
            ></Image>
          </Link>
          <div className="md:visible md:flex hidden">
            <Link
              href={"/"}
              className="ml-20 text-[#5B2205] text-xl hover:text-[#5b220596] mt-1 hover:mt-0"
            >
              Appartments
            </Link>
            <Link
              href={"/"}
              className="ml-5 text-[#5B2205] text-xl hover:text-[#5b220596] mt-1 hover:mt-0"
            >
              About Us
            </Link>
            <Link
              href={"/"}
              className="ml-5 text-[#5B2205] text-xl hover:text-[#5b220596] mt-1 hover:mt-0"
            >
              Contact
            </Link>
            <Link
              href={"/"}
              className="ml-5 text-[#5B2205] text-xl hover:text-[#5b220596] mt-1 hover:mt-0"
            >
              Login
            </Link>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
